### ISSUE TITLE
ESP32-P4+ESP32-C5 fail to set ax or ac protocol mode with iperf example (EHM-55)

### ISSUE THREAD

**Issue by ceerqingtingml** [espressif/esp-hosted-mcu#52]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

set ax or ac protocol mode successfully in AP mode.

### Actual behavior (suspected bug)

fail to set ax or ac protocol in AP mode

### Error logs or terminal output

```shell

```

## SDK version
esp-hosted-mcu commit: 22c924eeec99df03ba84430077c6a4585a32944f   
esp-idf release/v5.5 commit: 28ac0243bb65f2d3ad6fc4e90c54365b10d435b9

## Hardware
custom P4+C5 board(SDIO interface)

## Project to reproduce
P4 running the iperf example, do the changes below to  iperf/main/idf_component.yml:
```
  espressif/esp_wifi_remote:
    version: "~0.10.0"
    rules:
      - if: "target in [esp32p4, esp32h2]"
  esp_hosted:
    path: ../components/esp_hosted
    rules:
      - if: "target in [esp32p4, esp32h2]"
```
create components folder under iperf, git clone esp-hosted-mcu(22c924eeec99df03ba84430077c6a4585a32944f) under components.

C5 running iperf/components/esp_hosted/slave

## Test result
Fail to set ac or ac protocol in AP mode on P4

![Image](https://github.com/user-attachments/assets/0b6522f0-9382-42a0-b612-35a105109535)

If running iperf example directley on C5 board, it is successful.

![Image](https://github.com/user-attachments/assets/62161c65-6c9e-49e5-acf4-f7153aeefa09)

### Project release version

esp-hosted-mcu commit: 22c924eeec99df03ba84430077c6a4585a32944f   esp-idf release/v5.5 commit: 28ac0243bb65f2d3ad6fc4e90c54365b10d435b9

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

Ubuntu 22.04.5 LTS

### Shell

ZSH
